/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Settings = {
	_id: string;
	_type: 'settings';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	siteTitle?: string;
	googleAnalyticsId?: string;
	metadata?: Metadata;
};

export type Navigation = {
	_type: 'navigation';
	links?: Array<
		{
			_key: string;
		} & Link
	>;
};

export type Link = {
	_type: 'link';
	reference?:
		| {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'page';
		  }
		| {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'homepage';
		  };
	href?: string;
	label?: string;
};

export type Footer = {
	_type: 'footer';
	links?: Array<
		{
			_key: string;
		} & Link
	>;
};

export type RichTextSimple = Array<{
	children?: Array<{
		marks?: Array<string>;
		text?: string;
		_type: 'span';
		_key: string;
	}>;
	style?: 'normal';
	listItem?: never;
	markDefs?: Array<
		| ({
				_key: string;
		  } & InternalLink)
		| ({
				_key: string;
		  } & ExternalLink)
	>;
	level?: number;
	_type: 'block';
	_key: string;
}>;

export type RichTextMinimal = Array<{
	children?: Array<{
		marks?: Array<string>;
		text?: string;
		_type: 'span';
		_key: string;
	}>;
	style?: 'normal';
	listItem?: never;
	markDefs?: null;
	level?: number;
	_type: 'block';
	_key: string;
}>;

export type RichText = Array<{
	children?: Array<{
		marks?: Array<string>;
		text?: string;
		_type: 'span';
		_key: string;
	}>;
	style?: 'normal' | 'h1' | 'h2';
	listItem?: 'bullet' | 'number';
	markDefs?: Array<
		| ({
				_key: string;
		  } & InternalLink)
		| ({
				_key: string;
		  } & ExternalLink)
	>;
	level?: number;
	_type: 'block';
	_key: string;
}>;

export type ExternalLink = {
	_type: 'externalLink';
	href?: string;
	blank?: boolean;
};

export type InternalLink = {
	_type: 'internalLink';
	reference?:
		| {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'page';
		  }
		| {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'homepage';
		  };
};

export type Homepage = {
	_id: string;
	_type: 'homepage';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	homepageMetaTitle?: string;
	modules?: Array<
		| ({
				_key: string;
		  } & TextBlock)
		| ({
				_key: string;
		  } & MediaBlock)
	>;
};

export type Page = {
	_id: string;
	_type: 'page';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	modules?: Array<
		| ({
				_key: string;
		  } & TextBlock)
		| ({
				_key: string;
		  } & MediaBlock)
	>;
	metadata?: Metadata;
};

export type Metadata = {
	_type: 'metadata';
	description?: string;
	image?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
};

export type Modules = Array<
	| ({
			_key: string;
	  } & TextBlock)
	| ({
			_key: string;
	  } & MediaBlock)
>;

export type TextBlock = {
	_type: 'textBlock';
	richText?: RichText;
};

export type MediaBlock = {
	_type: 'mediaBlock';
	media?: Media;
};

export type Media = {
	_type: 'media';
	image?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	video?: MuxVideo;
	showVideoControls?: boolean;
	posterFrame?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
};

export type MuxVideo = {
	_type: 'mux.video';
	asset?: {
		_ref: string;
		_type: 'reference';
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: 'mux.videoAsset';
	};
};

export type MuxVideoAsset = {
	_id: string;
	_type: 'mux.videoAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	status?: string;
	assetId?: string;
	playbackId?: string;
	filename?: string;
	thumbTime?: number;
	data?: MuxAssetData;
};

export type MuxAssetData = {
	_type: 'mux.assetData';
	resolution_tier?: string;
	upload_id?: string;
	created_at?: string;
	id?: string;
	status?: string;
	max_stored_resolution?: string;
	passthrough?: string;
	encoding_tier?: string;
	master_access?: string;
	aspect_ratio?: string;
	duration?: number;
	max_stored_frame_rate?: number;
	mp4_support?: string;
	max_resolution_tier?: string;
	tracks?: Array<
		{
			_key: string;
		} & MuxTrack
	>;
	playback_ids?: Array<
		{
			_key: string;
		} & MuxPlaybackId
	>;
	static_renditions?: MuxStaticRenditions;
};

export type MuxStaticRenditions = {
	_type: 'mux.staticRenditions';
	status?: string;
	files?: Array<
		{
			_key: string;
		} & MuxStaticRenditionFile
	>;
};

export type MuxStaticRenditionFile = {
	_type: 'mux.staticRenditionFile';
	ext?: string;
	name?: string;
	width?: number;
	bitrate?: number;
	filesize?: number;
	height?: number;
};

export type MuxPlaybackId = {
	_type: 'mux.playbackId';
	id?: string;
	policy?: string;
};

export type MuxTrack = {
	_type: 'mux.track';
	id?: string;
	type?: string;
	max_width?: number;
	max_frame_rate?: number;
	duration?: number;
	max_height?: number;
};

export type MediaTag = {
	_id: string;
	_type: 'media.tag';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: Slug;
};

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch';
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: 'sanity.imagePalette';
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions';
	height?: number;
	width?: number;
	aspectRatio?: number;
};

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot';
	x?: number;
	y?: number;
	height?: number;
	width?: number;
};

export type SanityImageCrop = {
	_type: 'sanity.imageCrop';
	top?: number;
	bottom?: number;
	left?: number;
	right?: number;
};

export type SanityFileAsset = {
	_id: string;
	_type: 'sanity.fileAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
	_id: string;
	_type: 'sanity.imageAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata';
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type Geopoint = {
	_type: 'geopoint';
	lat?: number;
	lng?: number;
	alt?: number;
};

export type Slug = {
	_type: 'slug';
	current?: string;
	source?: string;
};

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData';
	name?: string;
	id?: string;
	url?: string;
};

export type AllSanitySchemaTypes =
	| Settings
	| Navigation
	| Link
	| Footer
	| RichTextSimple
	| RichTextMinimal
	| RichText
	| ExternalLink
	| InternalLink
	| Homepage
	| Page
	| Metadata
	| Modules
	| TextBlock
	| MediaBlock
	| Media
	| MuxVideo
	| MuxVideoAsset
	| MuxAssetData
	| MuxStaticRenditions
	| MuxStaticRenditionFile
	| MuxPlaybackId
	| MuxTrack
	| MediaTag
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageHotspot
	| SanityImageCrop
	| SanityFileAsset
	| SanityImageAsset
	| SanityImageMetadata
	| Geopoint
	| Slug
	| SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../web/src/lib/sanity/queries.ts
// Variable: LINK_PROJECTION
// Query: {  label,  href,  reference-> {    _type,    title,    "slug": slug.current   }}
export type LINK_PROJECTIONResult = {
	label: never;
	href: never;
	reference: never;
};
// Variable: RICH_TEXT_PROJECTION
// Query: {  ..., "markDefs": coalesce(    markDefs[]{      ...,      _type == "internalLink" => {        'type': @.reference->_type,        "slug": @.reference->slug.current      }    },     []  )}
export type RICH_TEXT_PROJECTIONResult = never;
// Variable: MEDIA_PROJECTION
// Query: {  "_type": "mediaProjection",  "asset": select(    defined(@.image) => {      "_type": "image",      "image": @.image    },    defined(@.video.asset) => {      "_type": "video",      "video": @.video.asset-> {        "playbackId": playbackId,        "aspect": data.aspect_ratio,        "showControls": ^.showVideoControls,        "posterFrame": ^.posterFrame      }    },    null  ),}
export type MEDIA_PROJECTIONResult = {
	_type: 'mediaProjection';
	asset: null;
};
// Variable: MODULES_PROJECTION
// Query: {  _type,  _key,  // groq  _type == 'mediaBlock' => {    media{  "_type": "mediaProjection",  "asset": select(    defined(@.image) => {      "_type": "image",      "image": @.image    },    defined(@.video.asset) => {      "_type": "video",      "video": @.video.asset-> {        "playbackId": playbackId,        "aspect": data.aspect_ratio,        "showControls": ^.showVideoControls,        "posterFrame": ^.posterFrame      }    },    null  ),}  },  // groq  _type == 'textBlock' => {    richText[]{  ..., "markDefs": coalesce(    markDefs[]{      ...,      _type == "internalLink" => {        'type': @.reference->_type,        "slug": @.reference->slug.current      }    },     []  )},  },}
export type MODULES_PROJECTIONResult = {
	_type: never;
	_key: never;
};
// Variable: PAGE_QUERY
// Query: *[_type == 'page' && slug.current == $slug][0]{    _type,    _id,    title,    metadata,    modules[]{  _type,  _key,  // groq  _type == 'mediaBlock' => {    media{  "_type": "mediaProjection",  "asset": select(    defined(@.image) => {      "_type": "image",      "image": @.image    },    defined(@.video.asset) => {      "_type": "video",      "video": @.video.asset-> {        "playbackId": playbackId,        "aspect": data.aspect_ratio,        "showControls": ^.showVideoControls,        "posterFrame": ^.posterFrame      }    },    null  ),}  },  // groq  _type == 'textBlock' => {    richText[]{  ..., "markDefs": coalesce(    markDefs[]{      ...,      _type == "internalLink" => {        'type': @.reference->_type,        "slug": @.reference->slug.current      }    },     []  )},  },},  }
export type PAGE_QUERYResult = {
	_type: 'page';
	_id: string;
	title: string | null;
	metadata: Metadata | null;
	modules: Array<
		| {
				_type: 'mediaBlock';
				_key: string;
				media: {
					_type: 'mediaProjection';
					asset:
						| {
								_type: 'image';
								image: {
									asset?: {
										_ref: string;
										_type: 'reference';
										_weak?: boolean;
										[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
									};
									media?: unknown;
									hotspot?: SanityImageHotspot;
									crop?: SanityImageCrop;
									_type: 'image';
								} | null;
						  }
						| {
								_type: 'video';
								video: {
									playbackId: string | null;
									aspect: string | null;
									showControls: boolean | null;
									posterFrame: {
										asset?: {
											_ref: string;
											_type: 'reference';
											_weak?: boolean;
											[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
										};
										media?: unknown;
										hotspot?: SanityImageHotspot;
										crop?: SanityImageCrop;
										_type: 'image';
									} | null;
								} | null;
						  }
						| null;
				} | null;
		  }
		| {
				_type: 'textBlock';
				_key: string;
				richText: Array<{
					children?: Array<{
						marks?: Array<string>;
						text?: string;
						_type: 'span';
						_key: string;
					}>;
					style?: 'h1' | 'h2' | 'normal';
					listItem?: 'bullet' | 'number';
					markDefs:
						| Array<never>
						| Array<
								| {
										_key: string;
										_type: 'externalLink';
										href?: string;
										blank?: boolean;
								  }
								| {
										_key: string;
										_type: 'internalLink';
										reference?:
											| {
													_ref: string;
													_type: 'reference';
													_weak?: boolean;
													[internalGroqTypeReferenceTo]?: 'homepage';
											  }
											| {
													_ref: string;
													_type: 'reference';
													_weak?: boolean;
													[internalGroqTypeReferenceTo]?: 'page';
											  };
										type: 'homepage' | 'page' | null;
										slug: string | null;
								  }
						  >;
					level?: number;
					_type: 'block';
					_key: string;
				}> | null;
		  }
	> | null;
} | null;
// Variable: HOMEPAGE_QUERY
// Query: *[_id == 'homepage'][0]{    modules[]{  _type,  _key,  // groq  _type == 'mediaBlock' => {    media{  "_type": "mediaProjection",  "asset": select(    defined(@.image) => {      "_type": "image",      "image": @.image    },    defined(@.video.asset) => {      "_type": "video",      "video": @.video.asset-> {        "playbackId": playbackId,        "aspect": data.aspect_ratio,        "showControls": ^.showVideoControls,        "posterFrame": ^.posterFrame      }    },    null  ),}  },  // groq  _type == 'textBlock' => {    richText[]{  ..., "markDefs": coalesce(    markDefs[]{      ...,      _type == "internalLink" => {        'type': @.reference->_type,        "slug": @.reference->slug.current      }    },     []  )},  },},  }
export type HOMEPAGE_QUERYResult =
	| {
			modules: null;
	  }
	| {
			modules: Array<
				| {
						_type: 'mediaBlock';
						_key: string;
						media: {
							_type: 'mediaProjection';
							asset:
								| {
										_type: 'image';
										image: {
											asset?: {
												_ref: string;
												_type: 'reference';
												_weak?: boolean;
												[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
											};
											media?: unknown;
											hotspot?: SanityImageHotspot;
											crop?: SanityImageCrop;
											_type: 'image';
										} | null;
								  }
								| {
										_type: 'video';
										video: {
											playbackId: string | null;
											aspect: string | null;
											showControls: boolean | null;
											posterFrame: {
												asset?: {
													_ref: string;
													_type: 'reference';
													_weak?: boolean;
													[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
												};
												media?: unknown;
												hotspot?: SanityImageHotspot;
												crop?: SanityImageCrop;
												_type: 'image';
											} | null;
										} | null;
								  }
								| null;
						} | null;
				  }
				| {
						_type: 'textBlock';
						_key: string;
						richText: Array<{
							children?: Array<{
								marks?: Array<string>;
								text?: string;
								_type: 'span';
								_key: string;
							}>;
							style?: 'h1' | 'h2' | 'normal';
							listItem?: 'bullet' | 'number';
							markDefs:
								| Array<never>
								| Array<
										| {
												_key: string;
												_type: 'externalLink';
												href?: string;
												blank?: boolean;
										  }
										| {
												_key: string;
												_type: 'internalLink';
												reference?:
													| {
															_ref: string;
															_type: 'reference';
															_weak?: boolean;
															[internalGroqTypeReferenceTo]?: 'homepage';
													  }
													| {
															_ref: string;
															_type: 'reference';
															_weak?: boolean;
															[internalGroqTypeReferenceTo]?: 'page';
													  };
												type: 'homepage' | 'page' | null;
												slug: string | null;
										  }
								  >;
							level?: number;
							_type: 'block';
							_key: string;
						}> | null;
				  }
			> | null;
	  }
	| null;
// Variable: SITE_QUERY
// Query: {  "footer": *[_id == "footer"][0]{    links[]{  label,  href,  reference-> {    _type,    title,    "slug": slug.current   }},  },  "navigation": *[_id == "navigation"][0]{    links[]{  label,  href,  reference-> {    _type,    title,    "slug": slug.current   }},  },  "settings": *[_id == "settings"][0]{    metadata,    siteTitle,    googleAnalyticsId,  },  "homepageTitle": *[_id == 'homepage'][0].homepageMetaTitle}
export type SITE_QUERYResult = {
	footer: {
		links: null;
	} | null;
	navigation: {
		links: null;
	} | null;
	settings:
		| {
				metadata: null;
				siteTitle: null;
				googleAnalyticsId: null;
		  }
		| {
				metadata: Metadata | null;
				siteTitle: null;
				googleAnalyticsId: null;
		  }
		| {
				metadata: SanityImageMetadata | null;
				siteTitle: null;
				googleAnalyticsId: null;
		  }
		| {
				metadata: Metadata | null;
				siteTitle: string | null;
				googleAnalyticsId: string | null;
		  }
		| null;
	homepageTitle: null | string;
};
// Variable: SITEMAP_QUERY
// Query: {  "homepage": *[_type == 'homepage'][0]{    _updatedAt,  },  "pages": *[_type == 'page'][]{     title,    "slug": slug.current,    _updatedAt,  }}
export type SITEMAP_QUERYResult = {
	homepage: {
		_updatedAt: string;
	} | null;
	pages: Array<{
		title: string | null;
		slug: string | null;
		_updatedAt: string;
	}>;
};

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
	interface SanityQueries {
		'{\n  label,\n  href,\n  reference-> {\n    _type,\n    title,\n    "slug": slug.current \n  }\n}': LINK_PROJECTIONResult;
		'{\n  ...,\n "markDefs": coalesce(\n    markDefs[]{\n      ...,\n      _type == "internalLink" => {\n        \'type\': @.reference->_type,\n        "slug": @.reference->slug.current\n      }\n    }, \n    []\n  )\n}': RICH_TEXT_PROJECTIONResult;
		'{\n  "_type": "mediaProjection",\n  "asset": select(\n    defined(@.image) => {\n      "_type": "image",\n      "image": @.image\n    },\n    defined(@.video.asset) => {\n      "_type": "video",\n      "video": @.video.asset-> {\n        "playbackId": playbackId,\n        "aspect": data.aspect_ratio,\n        "showControls": ^.showVideoControls,\n        "posterFrame": ^.posterFrame\n      }\n    },\n    null\n  ),\n}': MEDIA_PROJECTIONResult;
		'{\n  _type,\n  _key,\n  // groq\n  _type == \'mediaBlock\' => {\n    media{\n  "_type": "mediaProjection",\n  "asset": select(\n    defined(@.image) => {\n      "_type": "image",\n      "image": @.image\n    },\n    defined(@.video.asset) => {\n      "_type": "video",\n      "video": @.video.asset-> {\n        "playbackId": playbackId,\n        "aspect": data.aspect_ratio,\n        "showControls": ^.showVideoControls,\n        "posterFrame": ^.posterFrame\n      }\n    },\n    null\n  ),\n}\n  }\n,\n  // groq\n  _type == \'textBlock\' => {\n    richText[]{\n  ...,\n "markDefs": coalesce(\n    markDefs[]{\n      ...,\n      _type == "internalLink" => {\n        \'type\': @.reference->_type,\n        "slug": @.reference->slug.current\n      }\n    }, \n    []\n  )\n},\n  }\n,\n}\n': MODULES_PROJECTIONResult;
		'\n  *[_type == \'page\' && slug.current == $slug][0]{\n    _type,\n    _id,\n    title,\n    metadata,\n    modules[]{\n  _type,\n  _key,\n  // groq\n  _type == \'mediaBlock\' => {\n    media{\n  "_type": "mediaProjection",\n  "asset": select(\n    defined(@.image) => {\n      "_type": "image",\n      "image": @.image\n    },\n    defined(@.video.asset) => {\n      "_type": "video",\n      "video": @.video.asset-> {\n        "playbackId": playbackId,\n        "aspect": data.aspect_ratio,\n        "showControls": ^.showVideoControls,\n        "posterFrame": ^.posterFrame\n      }\n    },\n    null\n  ),\n}\n  }\n,\n  // groq\n  _type == \'textBlock\' => {\n    richText[]{\n  ...,\n "markDefs": coalesce(\n    markDefs[]{\n      ...,\n      _type == "internalLink" => {\n        \'type\': @.reference->_type,\n        "slug": @.reference->slug.current\n      }\n    }, \n    []\n  )\n},\n  }\n,\n}\n,\n  }\n': PAGE_QUERYResult;
		'\n  *[_id == \'homepage\'][0]{\n    modules[]{\n  _type,\n  _key,\n  // groq\n  _type == \'mediaBlock\' => {\n    media{\n  "_type": "mediaProjection",\n  "asset": select(\n    defined(@.image) => {\n      "_type": "image",\n      "image": @.image\n    },\n    defined(@.video.asset) => {\n      "_type": "video",\n      "video": @.video.asset-> {\n        "playbackId": playbackId,\n        "aspect": data.aspect_ratio,\n        "showControls": ^.showVideoControls,\n        "posterFrame": ^.posterFrame\n      }\n    },\n    null\n  ),\n}\n  }\n,\n  // groq\n  _type == \'textBlock\' => {\n    richText[]{\n  ...,\n "markDefs": coalesce(\n    markDefs[]{\n      ...,\n      _type == "internalLink" => {\n        \'type\': @.reference->_type,\n        "slug": @.reference->slug.current\n      }\n    }, \n    []\n  )\n},\n  }\n,\n}\n,\n  }\n': HOMEPAGE_QUERYResult;
		'{\n  "footer": *[_id == "footer"][0]{\n    links[]{\n  label,\n  href,\n  reference-> {\n    _type,\n    title,\n    "slug": slug.current \n  }\n},\n  },\n  "navigation": *[_id == "navigation"][0]{\n    links[]{\n  label,\n  href,\n  reference-> {\n    _type,\n    title,\n    "slug": slug.current \n  }\n},\n  },\n  "settings": *[_id == "settings"][0]{\n    metadata,\n    siteTitle,\n    googleAnalyticsId,\n  },\n  "homepageTitle": *[_id == \'homepage\'][0].homepageMetaTitle\n}': SITE_QUERYResult;
		'{\n  "homepage": *[_type == \'homepage\'][0]{\n    _updatedAt,\n  },\n\n  "pages": *[_type == \'page\'][]{ \n    title,\n    "slug": slug.current,\n    _updatedAt,\n  }\n}': SITEMAP_QUERYResult;
	}
}
