/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch';
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: 'sanity.imagePalette';
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions';
	height?: number;
	width?: number;
	aspectRatio?: number;
};

export type SanityFileAsset = {
	_id: string;
	_type: 'sanity.fileAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	source?: SanityAssetSourceData;
};

export type Geopoint = {
	_type: 'geopoint';
	lat?: number;
	lng?: number;
	alt?: number;
};

export type Settings = {
	_id: string;
	_type: 'settings';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	siteTitle?: string;
	metadata?: Metadata;
};

export type Navigation = {
	_type: 'navigation';
	links?: Array<
		{
			_key: string;
		} & Link
	>;
};

export type Homepage = {
	_id: string;
	_type: 'homepage';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	modules?: Array<
		| ({
				_key: string;
		  } & TextBlock)
		| ({
				_key: string;
		  } & MediaBlock)
	>;
};

export type Page = {
	_id: string;
	_type: 'page';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	modules?: Array<
		| ({
				_key: string;
		  } & TextBlock)
		| ({
				_key: string;
		  } & MediaBlock)
	>;
	metadata?: Metadata;
};

export type Footer = {
	_type: 'footer';
	links?: Array<
		{
			_key: string;
		} & Link
	>;
};

export type Metadata = {
	_type: 'metadata';
	description?: string;
	image?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
};

export type RichTextMinimal = Array<{
	children?: Array<{
		marks?: Array<string>;
		text?: string;
		_type: 'span';
		_key: string;
	}>;
	style?: 'normal';
	listItem?: never;
	markDefs?: null;
	level?: number;
	_type: 'block';
	_key: string;
}>;

export type RichText = Array<{
	children?: Array<{
		marks?: Array<string>;
		text?: string;
		_type: 'span';
		_key: string;
	}>;
	style?: 'normal' | 'h1' | 'h2' | 'h3' | 'blockquote';
	listItem?: 'bullet' | 'number';
	markDefs?: Array<{
		link?: Link;
		_type: 'link';
		_key: string;
	}>;
	level?: number;
	_type: 'block';
	_key: string;
}>;

export type Modules = Array<
	| ({
			_key: string;
	  } & TextBlock)
	| ({
			_key: string;
	  } & MediaBlock)
>;

export type TextBlock = {
	_type: 'textBlock';
	richText?: RichText;
};

export type Link = {
	_type: 'link';
	reference?:
		| {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'page';
		  }
		| {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'homepage';
		  };
	href?: string;
	label?: string;
};

export type MediaBlock = {
	_type: 'mediaBlock';
	media?: Media;
};

export type SanityImageCrop = {
	_type: 'sanity.imageCrop';
	top?: number;
	bottom?: number;
	left?: number;
	right?: number;
};

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot';
	x?: number;
	y?: number;
	height?: number;
	width?: number;
};

export type SanityImageAsset = {
	_id: string;
	_type: 'sanity.imageAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData';
	name?: string;
	id?: string;
	url?: string;
};

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata';
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type Media = {
	_type: 'media';
	image?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
};

export type MediaTag = {
	_id: string;
	_type: 'media.tag';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: Slug;
};

export type Slug = {
	_type: 'slug';
	current?: string;
	source?: string;
};

export type AllSanitySchemaTypes =
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityFileAsset
	| Geopoint
	| Settings
	| Navigation
	| Homepage
	| Page
	| Footer
	| Metadata
	| RichTextMinimal
	| RichText
	| Modules
	| TextBlock
	| Link
	| MediaBlock
	| SanityImageCrop
	| SanityImageHotspot
	| SanityImageAsset
	| SanityAssetSourceData
	| SanityImageMetadata
	| Media
	| MediaTag
	| Slug;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../web/src/sanity/queries.ts
// Variable: LINK_PROJECTION
// Query: {  label,  href,  reference-> {    _type,    title,    "slug": slug.current   }}
export type LINK_PROJECTIONResult = {
	label: never;
	href: never;
	reference: never;
};
// Variable: RICH_TEXT_PROJECTION
// Query: {  ...,  "markDefs": markDefs[]{    ...,    _type == 'link' => {      "link": @.link{  label,  href,  reference-> {    _type,    title,    "slug": slug.current   }}    }  }}
export type RICH_TEXT_PROJECTIONResult = never;
// Variable: MEDIA_PROJECTION
// Query: {  "image": @.media.image}
export type MEDIA_PROJECTIONResult = {
	image: never;
};
// Variable: MODULES_PROJECTION
// Query: {  _type,    _type == 'textBlock' => {    richText[]{  ...,  "markDefs": markDefs[]{    ...,    _type == 'link' => {      "link": @.link{  label,  href,  reference-> {    _type,    title,    "slug": slug.current   }}    }  }},  },  _type == 'mediaBlock' => {  "image": @.media.image}}
export type MODULES_PROJECTIONResult = {
	_type: never;
};
// Variable: PAGE_QUERY
// Query: *[_type == 'page' && slug.current == $slug][0]{    title,    metadata,    modules[]{  _type,    _type == 'textBlock' => {    richText[]{  ...,  "markDefs": markDefs[]{    ...,    _type == 'link' => {      "link": @.link{  label,  href,  reference-> {    _type,    title,    "slug": slug.current   }}    }  }},  },  _type == 'mediaBlock' => {  "image": @.media.image}},  }
export type PAGE_QUERYResult = {
	title: string | null;
	metadata: Metadata | null;
	modules: Array<
		| {
				_type: 'mediaBlock';
				image: {
					asset?: {
						_ref: string;
						_type: 'reference';
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
					};
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: 'image';
				} | null;
		  }
		| {
				_type: 'textBlock';
				richText: Array<{
					children?: Array<{
						marks?: Array<string>;
						text?: string;
						_type: 'span';
						_key: string;
					}>;
					style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'normal';
					listItem?: 'bullet' | 'number';
					markDefs: Array<{
						link: {
							label: string | null;
							href: string | null;
							reference:
								| {
										_type: 'homepage';
										title: string | null;
										slug: null;
								  }
								| {
										_type: 'page';
										title: string | null;
										slug: string | null;
								  }
								| null;
						} | null;
						_type: 'link';
						_key: string;
					}> | null;
					level?: number;
					_type: 'block';
					_key: string;
				}> | null;
		  }
	> | null;
} | null;
// Variable: HOMEPAGE_QUERY
// Query: *[_id == 'homepage'][0]{    modules[]{  _type,    _type == 'textBlock' => {    richText[]{  ...,  "markDefs": markDefs[]{    ...,    _type == 'link' => {      "link": @.link{  label,  href,  reference-> {    _type,    title,    "slug": slug.current   }}    }  }},  },  _type == 'mediaBlock' => {  "image": @.media.image}},  }
export type HOMEPAGE_QUERYResult =
	| {
			modules: null;
	  }
	| {
			modules: Array<
				| {
						_type: 'mediaBlock';
						image: {
							asset?: {
								_ref: string;
								_type: 'reference';
								_weak?: boolean;
								[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
							};
							hotspot?: SanityImageHotspot;
							crop?: SanityImageCrop;
							_type: 'image';
						} | null;
				  }
				| {
						_type: 'textBlock';
						richText: Array<{
							children?: Array<{
								marks?: Array<string>;
								text?: string;
								_type: 'span';
								_key: string;
							}>;
							style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'normal';
							listItem?: 'bullet' | 'number';
							markDefs: Array<{
								link: {
									label: string | null;
									href: string | null;
									reference:
										| {
												_type: 'homepage';
												title: string | null;
												slug: null;
										  }
										| {
												_type: 'page';
												title: string | null;
												slug: string | null;
										  }
										| null;
								} | null;
								_type: 'link';
								_key: string;
							}> | null;
							level?: number;
							_type: 'block';
							_key: string;
						}> | null;
				  }
			> | null;
	  }
	| null;
// Variable: SITE_QUERY
// Query: {  "footer": *[_id == "footer"][0]{    links[]{  label,  href,  reference-> {    _type,    title,    "slug": slug.current   }},  },  "navigation": *[_id == "navigation"][0],  "settings": *[_id == "settings"][0]{    metadata,    siteTitle,  },  "homepageTitle": *[_id == 'homepage'][0].title}
export type SITE_QUERYResult = {
	footer: {
		links: null;
	} | null;
	navigation:
		| {
				_id: string;
				_type: 'homepage';
				_createdAt: string;
				_updatedAt: string;
				_rev: string;
				title?: string;
				modules?: Array<
					| ({
							_key: string;
					  } & MediaBlock)
					| ({
							_key: string;
					  } & TextBlock)
				>;
		  }
		| {
				_id: string;
				_type: 'media.tag';
				_createdAt: string;
				_updatedAt: string;
				_rev: string;
				name?: Slug;
		  }
		| {
				_id: string;
				_type: 'page';
				_createdAt: string;
				_updatedAt: string;
				_rev: string;
				title?: string;
				slug?: Slug;
				modules?: Array<
					| ({
							_key: string;
					  } & MediaBlock)
					| ({
							_key: string;
					  } & TextBlock)
				>;
				metadata?: Metadata;
		  }
		| {
				_id: string;
				_type: 'sanity.fileAsset';
				_createdAt: string;
				_updatedAt: string;
				_rev: string;
				originalFilename?: string;
				label?: string;
				title?: string;
				description?: string;
				altText?: string;
				sha1hash?: string;
				extension?: string;
				mimeType?: string;
				size?: number;
				assetId?: string;
				uploadId?: string;
				path?: string;
				url?: string;
				source?: SanityAssetSourceData;
		  }
		| {
				_id: string;
				_type: 'sanity.imageAsset';
				_createdAt: string;
				_updatedAt: string;
				_rev: string;
				originalFilename?: string;
				label?: string;
				title?: string;
				description?: string;
				altText?: string;
				sha1hash?: string;
				extension?: string;
				mimeType?: string;
				size?: number;
				assetId?: string;
				uploadId?: string;
				path?: string;
				url?: string;
				metadata?: SanityImageMetadata;
				source?: SanityAssetSourceData;
		  }
		| {
				_id: string;
				_type: 'settings';
				_createdAt: string;
				_updatedAt: string;
				_rev: string;
				siteTitle?: string;
				metadata?: Metadata;
		  }
		| null;
	settings:
		| {
				metadata: null;
				siteTitle: null;
		  }
		| {
				metadata: Metadata | null;
				siteTitle: null;
		  }
		| {
				metadata: Metadata | null;
				siteTitle: string | null;
		  }
		| {
				metadata: SanityImageMetadata | null;
				siteTitle: null;
		  }
		| null;
	homepageTitle: string | null;
};

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
	interface SanityQueries {
		'{\n  label,\n  href,\n  reference-> {\n    _type,\n    title,\n    "slug": slug.current \n  }\n}': LINK_PROJECTIONResult;
		'{\n  ...,\n  "markDefs": markDefs[]{\n    ...,\n    _type == \'link\' => {\n      "link": @.link{\n  label,\n  href,\n  reference-> {\n    _type,\n    title,\n    "slug": slug.current \n  }\n}\n    }\n  }\n}': RICH_TEXT_PROJECTIONResult;
		'{\n  "image": @.media.image\n}': MEDIA_PROJECTIONResult;
		'{\n  _type,\n  \n  _type == \'textBlock\' => {\n    richText[]{\n  ...,\n  "markDefs": markDefs[]{\n    ...,\n    _type == \'link\' => {\n      "link": @.link{\n  label,\n  href,\n  reference-> {\n    _type,\n    title,\n    "slug": slug.current \n  }\n}\n    }\n  }\n},\n  },\n\n  _type == \'mediaBlock\' => {\n  "image": @.media.image\n}\n}': MODULES_PROJECTIONResult;
		'\n  *[_type == \'page\' && slug.current == $slug][0]{\n    title,\n    metadata,\n    modules[]{\n  _type,\n  \n  _type == \'textBlock\' => {\n    richText[]{\n  ...,\n  "markDefs": markDefs[]{\n    ...,\n    _type == \'link\' => {\n      "link": @.link{\n  label,\n  href,\n  reference-> {\n    _type,\n    title,\n    "slug": slug.current \n  }\n}\n    }\n  }\n},\n  },\n\n  _type == \'mediaBlock\' => {\n  "image": @.media.image\n}\n},\n  }\n': PAGE_QUERYResult;
		'\n  *[_id == \'homepage\'][0]{\n    modules[]{\n  _type,\n  \n  _type == \'textBlock\' => {\n    richText[]{\n  ...,\n  "markDefs": markDefs[]{\n    ...,\n    _type == \'link\' => {\n      "link": @.link{\n  label,\n  href,\n  reference-> {\n    _type,\n    title,\n    "slug": slug.current \n  }\n}\n    }\n  }\n},\n  },\n\n  _type == \'mediaBlock\' => {\n  "image": @.media.image\n}\n},\n  }\n': HOMEPAGE_QUERYResult;
		'{\n  "footer": *[_id == "footer"][0]{\n    links[]{\n  label,\n  href,\n  reference-> {\n    _type,\n    title,\n    "slug": slug.current \n  }\n},\n  },\n  "navigation": *[_id == "navigation"][0],\n  "settings": *[_id == "settings"][0]{\n    metadata,\n    siteTitle,\n  },\n  "homepageTitle": *[_id == \'homepage\'][0].title\n}': SITE_QUERYResult;
	}
}
