/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch';
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: 'sanity.imagePalette';
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions';
	height?: number;
	width?: number;
	aspectRatio?: number;
};

export type SanityFileAsset = {
	_id: string;
	_type: 'sanity.fileAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	source?: SanityAssetSourceData;
};

export type Geopoint = {
	_type: 'geopoint';
	lat?: number;
	lng?: number;
	alt?: number;
};

export type Settings = {
	_id: string;
	_type: 'settings';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	siteTitle?: string;
	metadata?: Metadata;
};

export type Link = {
	_type: 'link';
	reference?:
		| {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'page';
		  }
		| {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'homepage';
		  };
	href?: string;
	label?: string;
};

export type RichTextSimple = Array<{
	children?: Array<{
		marks?: Array<string>;
		text?: string;
		_type: 'span';
		_key: string;
	}>;
	style?: 'normal';
	listItem?: never;
	markDefs?: Array<
		| ({
				_key: string;
		  } & InternalLink)
		| ({
				_key: string;
		  } & ExternalLink)
	>;
	level?: number;
	_type: 'block';
	_key: string;
}>;

export type RichTextMinimal = Array<{
	children?: Array<{
		marks?: Array<string>;
		text?: string;
		_type: 'span';
		_key: string;
	}>;
	style?: 'normal';
	listItem?: never;
	markDefs?: null;
	level?: number;
	_type: 'block';
	_key: string;
}>;

export type RichText = Array<{
	children?: Array<{
		marks?: Array<string>;
		text?: string;
		_type: 'span';
		_key: string;
	}>;
	style?: 'normal' | 'h1' | 'h2';
	listItem?: 'bullet' | 'number';
	markDefs?: Array<
		| ({
				_key: string;
		  } & InternalLink)
		| ({
				_key: string;
		  } & ExternalLink)
	>;
	level?: number;
	_type: 'block';
	_key: string;
}>;

export type ExternalLink = {
	_type: 'externalLink';
	href?: string;
	blank?: boolean;
};

export type InternalLink = {
	_type: 'internalLink';
	reference?:
		| {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'homepage';
		  }
		| {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'caseStudy';
		  }
		| {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'page';
		  };
};

export type Page = {
	_id: string;
	_type: 'page';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	modules?: Array<
		| ({
				_key: string;
		  } & TextBlock)
		| ({
				_key: string;
		  } & MediaBlock)
		| ({
				_key: string;
		  } & Website)
		| ({
				_key: string;
		  } & Diptych)
	>;
	metadata?: Metadata;
};

export type Homepage = {
	_id: string;
	_type: 'homepage';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	context?: {
		_ref: string;
		_type: 'reference';
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: 'context';
	};
};

export type Modules = Array<
	| ({
			_key: string;
	  } & TextBlock)
	| ({
			_key: string;
	  } & MediaBlock)
	| ({
			_key: string;
	  } & Website)
	| ({
			_key: string;
	  } & Diptych)
>;

export type TextBlock = {
	_type: 'textBlock';
	content?: RichText;
	richText?: RichText;
};

export type MediaBlock = {
	_type: 'mediaBlock';
	media?: Media;
};

export type Context = {
	_id: string;
	_type: 'context';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	caseStudies?: Array<{
		_ref: string;
		_type: 'reference';
		_weak?: boolean;
		_key: string;
		[internalGroqTypeReferenceTo]?: 'caseStudy';
	}>;
};

export type CaseStudy = {
	_id: string;
	_type: 'caseStudy';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	date?: string;
	intro?: string;
	deliverables?: Array<string>;
	previewImage?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	description?: RichTextSimple;
	modules?: Modules;
	modulesV2?: Modules;
	metadata?: Metadata;
};

export type Metadata = {
	_type: 'metadata';
	description?: string;
	image?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
};

export type Playlist = {
	_id: string;
	_type: 'playlist';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	link?: string;
};

export type Info = {
	_id: string;
	_type: 'info';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	bio?: string;
	clients?: Array<string>;
	playlists?: Array<{
		_ref: string;
		_type: 'reference';
		_weak?: boolean;
		_key: string;
		[internalGroqTypeReferenceTo]?: 'playlist';
	}>;
	previewImage?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	slug?: Slug;
};

export type Website = {
	_type: 'website';
	media?: Media;
	showFrame?: boolean;
	theme?: {
		_ref: string;
		_type: 'reference';
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: 'webFrameTheme';
	};
	backgroundImg?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
};

export type WebFrameTheme = {
	_id: string;
	_type: 'webFrameTheme';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	background?: Color;
	frame?: Color;
	dots?: Color;
};

export type Diptych = {
	_type: 'diptych';
	items?: Array<
		| ({
				_key: string;
		  } & DiptychMedia)
		| ({
				_key: string;
		  } & DiptychText)
	>;
};

export type DiptychText = {
	_type: 'diptych.text';
	richText?: RichText;
};

export type DiptychMedia = {
	_type: 'diptych.media';
	media?: Media;
};

export type SanityImageCrop = {
	_type: 'sanity.imageCrop';
	top?: number;
	bottom?: number;
	left?: number;
	right?: number;
};

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot';
	x?: number;
	y?: number;
	height?: number;
	width?: number;
};

export type SanityImageAsset = {
	_id: string;
	_type: 'sanity.imageAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData';
	name?: string;
	id?: string;
	url?: string;
};

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata';
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type Media = {
	_type: 'media';
	image?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	video?: MuxVideo;
	showVideoControls?: boolean;
	posterFrame?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
};

export type Color = {
	_type: 'color';
	hex?: string;
	alpha?: number;
	hsl?: HslaColor;
	hsv?: HsvaColor;
	rgb?: RgbaColor;
};

export type RgbaColor = {
	_type: 'rgbaColor';
	r?: number;
	g?: number;
	b?: number;
	a?: number;
};

export type HsvaColor = {
	_type: 'hsvaColor';
	h?: number;
	s?: number;
	v?: number;
	a?: number;
};

export type HslaColor = {
	_type: 'hslaColor';
	h?: number;
	s?: number;
	l?: number;
	a?: number;
};

export type MuxVideo = {
	_type: 'mux.video';
	asset?: {
		_ref: string;
		_type: 'reference';
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: 'mux.videoAsset';
	};
};

export type MuxVideoAsset = {
	_type: 'mux.videoAsset';
	status?: string;
	assetId?: string;
	playbackId?: string;
	filename?: string;
	thumbTime?: number;
	data?: MuxAssetData;
};

export type MuxAssetData = {
	_type: 'mux.assetData';
	resolution_tier?: string;
	upload_id?: string;
	created_at?: string;
	id?: string;
	status?: string;
	max_stored_resolution?: string;
	passthrough?: string;
	encoding_tier?: string;
	master_access?: string;
	aspect_ratio?: string;
	duration?: number;
	max_stored_frame_rate?: number;
	mp4_support?: string;
	max_resolution_tier?: string;
	tracks?: Array<
		{
			_key: string;
		} & MuxTrack
	>;
	playback_ids?: Array<
		{
			_key: string;
		} & MuxPlaybackId
	>;
	static_renditions?: MuxStaticRenditions;
};

export type MuxStaticRenditions = {
	_type: 'mux.staticRenditions';
	status?: string;
	files?: Array<
		{
			_key: string;
		} & MuxStaticRenditionFile
	>;
};

export type MuxStaticRenditionFile = {
	_type: 'mux.staticRenditionFile';
	ext?: string;
	name?: string;
	width?: number;
	bitrate?: number;
	filesize?: number;
	height?: number;
};

export type MuxPlaybackId = {
	_type: 'mux.playbackId';
	id?: string;
	policy?: string;
};

export type MuxTrack = {
	_type: 'mux.track';
	id?: string;
	type?: string;
	max_width?: number;
	max_frame_rate?: number;
	duration?: number;
	max_height?: number;
};

export type MediaTag = {
	_id: string;
	_type: 'media.tag';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: Slug;
};

export type Slug = {
	_type: 'slug';
	current?: string;
	source?: string;
};

export type AllSanitySchemaTypes =
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityFileAsset
	| Geopoint
	| Settings
	| Link
	| RichTextSimple
	| RichTextMinimal
	| RichText
	| ExternalLink
	| InternalLink
	| Page
	| Homepage
	| Modules
	| TextBlock
	| MediaBlock
	| Context
	| CaseStudy
	| Metadata
	| Playlist
	| Info
	| Website
	| WebFrameTheme
	| Diptych
	| DiptychText
	| DiptychMedia
	| SanityImageCrop
	| SanityImageHotspot
	| SanityImageAsset
	| SanityAssetSourceData
	| SanityImageMetadata
	| Media
	| Color
	| RgbaColor
	| HsvaColor
	| HslaColor
	| MuxVideo
	| MuxVideoAsset
	| MuxAssetData
	| MuxStaticRenditions
	| MuxStaticRenditionFile
	| MuxPlaybackId
	| MuxTrack
	| MediaTag
	| Slug;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../web/src/sanity/queries.ts
// Variable: LINK_PROJECTION
// Query: {  label,  href,  reference-> {    _type,    title,    "slug": slug.current   }}
export type LINK_PROJECTIONResult = {
	label: never;
	href: never;
	reference: never;
};
// Variable: RICH_TEXT_PROJECTION
// Query: {  ..., "markDefs": coalesce(    markDefs[]{      ...,      _type == "internalLink" => {        'type': @.reference->_type,        "slug": @.reference->slug.current      }    },     []  )}
export type RICH_TEXT_PROJECTIONResult = never;
// Variable: MEDIA_PROJECTION
// Query: {  "image": image,  "video": video.asset->{    "id": playbackId,    "aspect": data.aspect_ratio,    "showControls": ^.showVideoControls,    "posterFrame": ^.posterFrame  }}
export type MEDIA_PROJECTIONResult = {
	image: never;
	video: never;
};
// Variable: MODULES_PROJECTION
// Query: {  _type,  // groq  _type == 'mediaBlock' => {    media{  "image": image,  "video": video.asset->{    "id": playbackId,    "aspect": data.aspect_ratio,    "showControls": ^.showVideoControls,    "posterFrame": ^.posterFrame  }}  },  // groq  _type == 'textBlock' => {    richText[]{  ..., "markDefs": coalesce(    markDefs[]{      ...,      _type == "internalLink" => {        'type': @.reference->_type,        "slug": @.reference->slug.current      }    },     []  )},  },  //groq  _type == 'website' => {    theme->{      "dots": dots.hex,      "frame": frame.hex,      "background": background.hex,    },    backgroundImg,    showFrame,    media{  "image": image,  "video": video.asset->{    "id": playbackId,    "aspect": data.aspect_ratio,    "showControls": ^.showVideoControls,    "posterFrame": ^.posterFrame  }},  }}
export type MODULES_PROJECTIONResult = {
	_type: never;
};
// Variable: PAGE_QUERY
// Query: *[_type == 'page' && slug.current == $slug][0]{    title,    metadata,    modules[]{  _type,  // groq  _type == 'mediaBlock' => {    media{  "image": image,  "video": video.asset->{    "id": playbackId,    "aspect": data.aspect_ratio,    "showControls": ^.showVideoControls,    "posterFrame": ^.posterFrame  }}  },  // groq  _type == 'textBlock' => {    richText[]{  ..., "markDefs": coalesce(    markDefs[]{      ...,      _type == "internalLink" => {        'type': @.reference->_type,        "slug": @.reference->slug.current      }    },     []  )},  },  //groq  _type == 'website' => {    theme->{      "dots": dots.hex,      "frame": frame.hex,      "background": background.hex,    },    backgroundImg,    showFrame,    media{  "image": image,  "video": video.asset->{    "id": playbackId,    "aspect": data.aspect_ratio,    "showControls": ^.showVideoControls,    "posterFrame": ^.posterFrame  }},  }},  }
export type PAGE_QUERYResult = {
	title: string | null;
	metadata: Metadata | null;
	modules: Array<
		| {
				_type: 'diptych';
		  }
		| {
				_type: 'mediaBlock';
				media: {
					image: {
						asset?: {
							_ref: string;
							_type: 'reference';
							_weak?: boolean;
							[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
						};
						hotspot?: SanityImageHotspot;
						crop?: SanityImageCrop;
						_type: 'image';
					} | null;
					video: null;
				} | null;
		  }
		| {
				_type: 'textBlock';
				richText: Array<{
					children?: Array<{
						marks?: Array<string>;
						text?: string;
						_type: 'span';
						_key: string;
					}>;
					style?: 'h1' | 'h2' | 'normal';
					listItem?: 'bullet' | 'number';
					markDefs:
						| Array<never>
						| Array<
								| {
										_key: string;
										_type: 'externalLink';
										href?: string;
										blank?: boolean;
								  }
								| {
										_key: string;
										_type: 'internalLink';
										reference?:
											| {
													_ref: string;
													_type: 'reference';
													_weak?: boolean;
													[internalGroqTypeReferenceTo]?: 'caseStudy';
											  }
											| {
													_ref: string;
													_type: 'reference';
													_weak?: boolean;
													[internalGroqTypeReferenceTo]?: 'homepage';
											  }
											| {
													_ref: string;
													_type: 'reference';
													_weak?: boolean;
													[internalGroqTypeReferenceTo]?: 'page';
											  };
										type: 'caseStudy' | 'homepage' | 'page' | null;
										slug: string | null;
								  }
						  >;
					level?: number;
					_type: 'block';
					_key: string;
				}> | null;
		  }
		| {
				_type: 'website';
				theme: {
					dots: string | null;
					frame: string | null;
					background: string | null;
				} | null;
				backgroundImg: {
					asset?: {
						_ref: string;
						_type: 'reference';
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
					};
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: 'image';
				} | null;
				showFrame: boolean | null;
				media: {
					image: {
						asset?: {
							_ref: string;
							_type: 'reference';
							_weak?: boolean;
							[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
						};
						hotspot?: SanityImageHotspot;
						crop?: SanityImageCrop;
						_type: 'image';
					} | null;
					video: null;
				} | null;
		  }
	> | null;
} | null;
// Variable: CASE_STUDY_QUERY
// Query: *[_type == 'caseStudy' && slug.current == $slug][0]{    intro,    deliverables,    date,    title,    description,    metadata,    "modules": modulesV2[]{  _type,  // groq  _type == 'mediaBlock' => {    media{  "image": image,  "video": video.asset->{    "id": playbackId,    "aspect": data.aspect_ratio,    "showControls": ^.showVideoControls,    "posterFrame": ^.posterFrame  }}  },  // groq  _type == 'textBlock' => {    richText[]{  ..., "markDefs": coalesce(    markDefs[]{      ...,      _type == "internalLink" => {        'type': @.reference->_type,        "slug": @.reference->slug.current      }    },     []  )},  },  //groq  _type == 'website' => {    theme->{      "dots": dots.hex,      "frame": frame.hex,      "background": background.hex,    },    backgroundImg,    showFrame,    media{  "image": image,  "video": video.asset->{    "id": playbackId,    "aspect": data.aspect_ratio,    "showControls": ^.showVideoControls,    "posterFrame": ^.posterFrame  }},  }},  }
export type CASE_STUDY_QUERYResult = {
	intro: string | null;
	deliverables: Array<string> | null;
	date: string | null;
	title: string | null;
	description: RichTextSimple | null;
	metadata: Metadata | null;
	modules: Array<
		| {
				_type: 'diptych';
		  }
		| {
				_type: 'mediaBlock';
				media: {
					image: {
						asset?: {
							_ref: string;
							_type: 'reference';
							_weak?: boolean;
							[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
						};
						hotspot?: SanityImageHotspot;
						crop?: SanityImageCrop;
						_type: 'image';
					} | null;
					video: null;
				} | null;
		  }
		| {
				_type: 'textBlock';
				richText: Array<{
					children?: Array<{
						marks?: Array<string>;
						text?: string;
						_type: 'span';
						_key: string;
					}>;
					style?: 'h1' | 'h2' | 'normal';
					listItem?: 'bullet' | 'number';
					markDefs:
						| Array<never>
						| Array<
								| {
										_key: string;
										_type: 'externalLink';
										href?: string;
										blank?: boolean;
								  }
								| {
										_key: string;
										_type: 'internalLink';
										reference?:
											| {
													_ref: string;
													_type: 'reference';
													_weak?: boolean;
													[internalGroqTypeReferenceTo]?: 'caseStudy';
											  }
											| {
													_ref: string;
													_type: 'reference';
													_weak?: boolean;
													[internalGroqTypeReferenceTo]?: 'homepage';
											  }
											| {
													_ref: string;
													_type: 'reference';
													_weak?: boolean;
													[internalGroqTypeReferenceTo]?: 'page';
											  };
										type: 'caseStudy' | 'homepage' | 'page' | null;
										slug: string | null;
								  }
						  >;
					level?: number;
					_type: 'block';
					_key: string;
				}> | null;
		  }
		| {
				_type: 'website';
				theme: {
					dots: string | null;
					frame: string | null;
					background: string | null;
				} | null;
				backgroundImg: {
					asset?: {
						_ref: string;
						_type: 'reference';
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
					};
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: 'image';
				} | null;
				showFrame: boolean | null;
				media: {
					image: {
						asset?: {
							_ref: string;
							_type: 'reference';
							_weak?: boolean;
							[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
						};
						hotspot?: SanityImageHotspot;
						crop?: SanityImageCrop;
						_type: 'image';
					} | null;
					video: null;
				} | null;
		  }
	> | null;
} | null;
// Variable: SITE_QUERY
// Query: {  "homepageTitle": *[_id == 'homepage'][0].title,  "settings": *[_id == "settings"][0]{    metadata,    siteTitle,  },  "context": coalesce(    *[_type == "context" && slug.current == $contextSlug][0],    *[_id == "homepage"][0].context->  ) {    title,    caseStudies[]->{      "slug": slug.current,      title,    }  },}
export type SITE_QUERYResult = {
	homepageTitle: string | null;
	settings:
		| {
				metadata: null;
				siteTitle: null;
		  }
		| {
				metadata: Metadata | null;
				siteTitle: null;
		  }
		| {
				metadata: Metadata | null;
				siteTitle: string | null;
		  }
		| {
				metadata: SanityImageMetadata | null;
				siteTitle: null;
		  }
		| null;
	context: {
		title: string | null;
		caseStudies: Array<{
			slug: string | null;
			title: string | null;
		}> | null;
	} | null;
};
// Variable: SITEMAP_QUERY
// Query: {  "info": *[_id == 'info'][0],  "pages": *[_id == "homepage"][0].context->caseStudies[]->{     title,    "slug": slug.current,    _updatedAt,  }}
export type SITEMAP_QUERYResult = {
	info:
		| {
				_id: string;
				_type: 'caseStudy';
				_createdAt: string;
				_updatedAt: string;
				_rev: string;
				title?: string;
				slug?: Slug;
				date?: string;
				intro?: string;
				deliverables?: Array<string>;
				previewImage?: {
					asset?: {
						_ref: string;
						_type: 'reference';
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
					};
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: 'image';
				};
				description?: RichTextSimple;
				modules?: Modules;
				modulesV2?: Modules;
				metadata?: Metadata;
		  }
		| {
				_id: string;
				_type: 'context';
				_createdAt: string;
				_updatedAt: string;
				_rev: string;
				title?: string;
				slug?: Slug;
				caseStudies?: Array<{
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					_key: string;
					[internalGroqTypeReferenceTo]?: 'caseStudy';
				}>;
		  }
		| {
				_id: string;
				_type: 'homepage';
				_createdAt: string;
				_updatedAt: string;
				_rev: string;
				title?: string;
				context?: {
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: 'context';
				};
		  }
		| {
				_id: string;
				_type: 'info';
				_createdAt: string;
				_updatedAt: string;
				_rev: string;
				title?: string;
				bio?: string;
				clients?: Array<string>;
				playlists?: Array<{
					_ref: string;
					_type: 'reference';
					_weak?: boolean;
					_key: string;
					[internalGroqTypeReferenceTo]?: 'playlist';
				}>;
				previewImage?: {
					asset?: {
						_ref: string;
						_type: 'reference';
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
					};
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: 'image';
				};
				slug?: Slug;
		  }
		| {
				_id: string;
				_type: 'media.tag';
				_createdAt: string;
				_updatedAt: string;
				_rev: string;
				name?: Slug;
		  }
		| {
				_id: string;
				_type: 'page';
				_createdAt: string;
				_updatedAt: string;
				_rev: string;
				title?: string;
				slug?: Slug;
				modules?: Array<
					| ({
							_key: string;
					  } & Diptych)
					| ({
							_key: string;
					  } & MediaBlock)
					| ({
							_key: string;
					  } & TextBlock)
					| ({
							_key: string;
					  } & Website)
				>;
				metadata?: Metadata;
		  }
		| {
				_id: string;
				_type: 'playlist';
				_createdAt: string;
				_updatedAt: string;
				_rev: string;
				title?: string;
				slug?: Slug;
				link?: string;
		  }
		| {
				_id: string;
				_type: 'sanity.fileAsset';
				_createdAt: string;
				_updatedAt: string;
				_rev: string;
				originalFilename?: string;
				label?: string;
				title?: string;
				description?: string;
				altText?: string;
				sha1hash?: string;
				extension?: string;
				mimeType?: string;
				size?: number;
				assetId?: string;
				uploadId?: string;
				path?: string;
				url?: string;
				source?: SanityAssetSourceData;
		  }
		| {
				_id: string;
				_type: 'sanity.imageAsset';
				_createdAt: string;
				_updatedAt: string;
				_rev: string;
				originalFilename?: string;
				label?: string;
				title?: string;
				description?: string;
				altText?: string;
				sha1hash?: string;
				extension?: string;
				mimeType?: string;
				size?: number;
				assetId?: string;
				uploadId?: string;
				path?: string;
				url?: string;
				metadata?: SanityImageMetadata;
				source?: SanityAssetSourceData;
		  }
		| {
				_id: string;
				_type: 'settings';
				_createdAt: string;
				_updatedAt: string;
				_rev: string;
				siteTitle?: string;
				metadata?: Metadata;
		  }
		| {
				_id: string;
				_type: 'webFrameTheme';
				_createdAt: string;
				_updatedAt: string;
				_rev: string;
				title?: string;
				background?: Color;
				frame?: Color;
				dots?: Color;
		  }
		| null;
	pages: Array<{
		title: string | null;
		slug: string | null;
		_updatedAt: string;
	}> | null;
};

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
	interface SanityQueries {
		'{\n  label,\n  href,\n  reference-> {\n    _type,\n    title,\n    "slug": slug.current \n  }\n}': LINK_PROJECTIONResult;
		'{\n  ...,\n "markDefs": coalesce(\n    markDefs[]{\n      ...,\n      _type == "internalLink" => {\n        \'type\': @.reference->_type,\n        "slug": @.reference->slug.current\n      }\n    }, \n    []\n  )\n}': RICH_TEXT_PROJECTIONResult;
		'{\n  "image": image,\n  "video": video.asset->{\n    "id": playbackId,\n    "aspect": data.aspect_ratio,\n    "showControls": ^.showVideoControls,\n    "posterFrame": ^.posterFrame\n  }\n}': MEDIA_PROJECTIONResult;
		'{\n  _type,\n  // groq\n  _type == \'mediaBlock\' => {\n    media{\n  "image": image,\n  "video": video.asset->{\n    "id": playbackId,\n    "aspect": data.aspect_ratio,\n    "showControls": ^.showVideoControls,\n    "posterFrame": ^.posterFrame\n  }\n}\n  }\n,\n  // groq\n  _type == \'textBlock\' => {\n    richText[]{\n  ...,\n "markDefs": coalesce(\n    markDefs[]{\n      ...,\n      _type == "internalLink" => {\n        \'type\': @.reference->_type,\n        "slug": @.reference->slug.current\n      }\n    }, \n    []\n  )\n},\n  }\n,\n  //groq\n  _type == \'website\' => {\n    theme->{\n      "dots": dots.hex,\n      "frame": frame.hex,\n      "background": background.hex,\n    },\n    backgroundImg,\n    showFrame,\n    media{\n  "image": image,\n  "video": video.asset->{\n    "id": playbackId,\n    "aspect": data.aspect_ratio,\n    "showControls": ^.showVideoControls,\n    "posterFrame": ^.posterFrame\n  }\n},\n  }\n\n}\n': MODULES_PROJECTIONResult;
		'\n  *[_type == \'page\' && slug.current == $slug][0]{\n    title,\n    metadata,\n    modules[]{\n  _type,\n  // groq\n  _type == \'mediaBlock\' => {\n    media{\n  "image": image,\n  "video": video.asset->{\n    "id": playbackId,\n    "aspect": data.aspect_ratio,\n    "showControls": ^.showVideoControls,\n    "posterFrame": ^.posterFrame\n  }\n}\n  }\n,\n  // groq\n  _type == \'textBlock\' => {\n    richText[]{\n  ...,\n "markDefs": coalesce(\n    markDefs[]{\n      ...,\n      _type == "internalLink" => {\n        \'type\': @.reference->_type,\n        "slug": @.reference->slug.current\n      }\n    }, \n    []\n  )\n},\n  }\n,\n  //groq\n  _type == \'website\' => {\n    theme->{\n      "dots": dots.hex,\n      "frame": frame.hex,\n      "background": background.hex,\n    },\n    backgroundImg,\n    showFrame,\n    media{\n  "image": image,\n  "video": video.asset->{\n    "id": playbackId,\n    "aspect": data.aspect_ratio,\n    "showControls": ^.showVideoControls,\n    "posterFrame": ^.posterFrame\n  }\n},\n  }\n\n}\n,\n  }\n': PAGE_QUERYResult;
		'\n  *[_type == \'caseStudy\' && slug.current == $slug][0]{\n    intro,\n    deliverables,\n    date,\n    title,\n    description,\n    metadata,\n    "modules": modulesV2[]{\n  _type,\n  // groq\n  _type == \'mediaBlock\' => {\n    media{\n  "image": image,\n  "video": video.asset->{\n    "id": playbackId,\n    "aspect": data.aspect_ratio,\n    "showControls": ^.showVideoControls,\n    "posterFrame": ^.posterFrame\n  }\n}\n  }\n,\n  // groq\n  _type == \'textBlock\' => {\n    richText[]{\n  ...,\n "markDefs": coalesce(\n    markDefs[]{\n      ...,\n      _type == "internalLink" => {\n        \'type\': @.reference->_type,\n        "slug": @.reference->slug.current\n      }\n    }, \n    []\n  )\n},\n  }\n,\n  //groq\n  _type == \'website\' => {\n    theme->{\n      "dots": dots.hex,\n      "frame": frame.hex,\n      "background": background.hex,\n    },\n    backgroundImg,\n    showFrame,\n    media{\n  "image": image,\n  "video": video.asset->{\n    "id": playbackId,\n    "aspect": data.aspect_ratio,\n    "showControls": ^.showVideoControls,\n    "posterFrame": ^.posterFrame\n  }\n},\n  }\n\n}\n,\n  }\n': CASE_STUDY_QUERYResult;
		'{\n  "homepageTitle": *[_id == \'homepage\'][0].title,\n  "settings": *[_id == "settings"][0]{\n    metadata,\n    siteTitle,\n  },\n  "context": coalesce(\n    *[_type == "context" && slug.current == $contextSlug][0],\n    *[_id == "homepage"][0].context->\n  ) {\n    title,\n    caseStudies[]->{\n      "slug": slug.current,\n      title,\n    }\n  },\n}': SITE_QUERYResult;
		'{\n  "info": *[_id == \'info\'][0],\n  "pages": *[_id == "homepage"][0].context->caseStudies[]->{ \n    title,\n    "slug": slug.current,\n    _updatedAt,\n  }\n}': SITEMAP_QUERYResult;
	}
}
